# Feature Engineering

Feature Engineering = Creating better input features so the model learns better patterns.

# Dataset

In [25]:
import numpy as np
import pandas as pd

data = {
    "Age": [25, 30, 22, 35, 40, 28, 32, 45, 29, 50, 27],
    "Salary": [50000, 60000, 45000, 70000, 80000, 52000, 62000, 90000, 48000, 120000, 55000],
    "City": ["hyderabad", "chennai", "delhi", "mumbai", "hyderabad",
             "delhi", "chennai", "mumbai", "delhi", "hyderabad", "chennai"],
    "Experience_Level": ["junior", "mid", "junior", "senior", "senior",
                         "mid", "junior", "senior", "mid", "senior", "mid"],
    "Purchased": ["no", "yes", "no", "yes", "yes",
                  "no", "yes", "yes", "no", "yes", "no"]
}

df = pd.DataFrame(data)
print(df)


    Age  Salary       City Experience_Level Purchased
0    25   50000  hyderabad           junior        no
1    30   60000    chennai              mid       yes
2    22   45000      delhi           junior        no
3    35   70000     mumbai           senior       yes
4    40   80000  hyderabad           senior       yes
5    28   52000      delhi              mid        no
6    32   62000    chennai           junior       yes
7    45   90000     mumbai           senior       yes
8    29   48000      delhi              mid        no
9    50  120000  hyderabad           senior       yes
10   27   55000    chennai              mid        no


# Creating New Features

In [26]:
experience_map = {'junior':1, 'mid':2, 'senior':3}
df['Experience_Score'] = df['Experience_Level'].map(experience_map)

print(df[['Experience_Level','Experience_Score']].head())


  Experience_Level  Experience_Score
0           junior                 1
1              mid                 2
2           junior                 1
3           senior                 3
4           senior                 3


In [27]:
df

,Age,Salary,City,Experience_Level,Purchased,Experience_Score
0,25,50000,hyderabad,junior,no,1
1,30,60000,chennai,mid,yes,2
2,22,45000,delhi,junior,no,1
3,35,70000,mumbai,senior,yes,3
4,40,80000,hyderabad,senior,yes,3
5,28,52000,delhi,mid,no,2
6,32,62000,chennai,junior,yes,1
7,45,90000,mumbai,senior,yes,3
8,29,48000,delhi,mid,no,2
9,50,120000,hyderabad,senior,yes,3


Why useful?

Models work better with meaningful numeric representation.

# Binning (Discretization)

In [28]:
# Convert continuous variable to categories.
df['Age_Group'] = pd.cut(df['Age'], bins=[18,30,45,60], labels=['Young','Adult','Senior'])

print(df[['Age','Age_Group']])


    Age Age_Group
0    25     Young
1    30     Young
2    22     Young
3    35     Adult
4    40     Adult
5    28     Young
6    32     Adult
7    45     Adult
8    29     Young
9    50    Senior
10   27     Young


In [29]:
df

,Age,Salary,City,Experience_Level,Purchased,Experience_Score,Age_Group
0,25,50000,hyderabad,junior,no,1,Young
1,30,60000,chennai,mid,yes,2,Young
2,22,45000,delhi,junior,no,1,Young
3,35,70000,mumbai,senior,yes,3,Adult
4,40,80000,hyderabad,senior,yes,3,Adult
5,28,52000,delhi,mid,no,2,Young
6,32,62000,chennai,junior,yes,1,Adult
7,45,90000,mumbai,senior,yes,3,Adult
8,29,48000,delhi,mid,no,2,Young
9,50,120000,hyderabad,senior,yes,3,Senior


When to use?

✔ Tree models
✔ When relationship is non-linear
✔ Business rule segmentation

# Log Transformation

In [30]:
# Used when data is skewed.
df['Salary_Log'] = np.log(df['Salary'])

print(df[['Salary','Salary_Log']].head())


   Salary  Salary_Log
0   50000   10.819778
1   60000   11.002100
2   45000   10.714418
3   70000   11.156251
4   80000   11.289782


When to use?

✔ Salary
✔ House prices
✔ Skewed distributions

Log reduces effect of extreme values.

# Interaction Features

In [31]:
# Create relationship between two features.
df['Age_Salary_Interaction'] = df['Age'] * df['Salary']

print(df[['Age','Salary','Age_Salary_Interaction']].head())


   Age  Salary  Age_Salary_Interaction
0   25   50000                 1250000
1   30   60000                 1800000
2   22   45000                  990000
3   35   70000                 2450000
4   40   80000                 3200000


In [32]:
df

,Age,Salary,City,Experience_Level,Purchased,Experience_Score,Age_Group,Salary_Log,Age_Salary_Interaction
0,25,50000,hyderabad,junior,no,1,Young,10.819778,1250000
1,30,60000,chennai,mid,yes,2,Young,11.002100,1800000
2,22,45000,delhi,junior,no,1,Young,10.714418,990000
3,35,70000,mumbai,senior,yes,3,Adult,11.156251,2450000
4,40,80000,hyderabad,senior,yes,3,Adult,11.289782,3200000
5,28,52000,delhi,mid,no,2,Young,10.858999,1456000
6,32,62000,chennai,junior,yes,1,Adult,11.034890,1984000
7,45,90000,mumbai,senior,yes,3,Adult,11.407565,4050000
8,29,48000,delhi,mid,no,2,Young,10.778956,1392000
9,50,120000,hyderabad,senior,yes,3,Senior,11.695247,6000000


Why useful?

Sometimes:

Age alone not strong

Salary alone not strong

But combined they are powerful

# Polynomial Features

In [33]:
# Automatically generate higher-degree features.
from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(degree=2, include_bias=False)

poly_features = poly.fit_transform(df[['Age','Salary']])

print(poly.get_feature_names_out(['Age','Salary']))
print(poly_features[:3])


['Age' 'Salary' 'Age^2' 'Age Salary' 'Salary^2']
[[2.500e+01 5.000e+04 6.250e+02 1.250e+06 2.500e+09]
 [3.000e+01 6.000e+04 9.000e+02 1.800e+06 3.600e+09]
 [2.200e+01 4.500e+04 4.840e+02 9.900e+05 2.025e+09]]


# Domain-Based Features

In [34]:
df['Income_Category'] = np.where(df['Salary'] > 70000, 
                                 'High', 'Low')

print(df[['Salary','Income_Category']].head())


   Salary Income_Category
0   50000             Low
1   60000             Low
2   45000             Low
3   70000             Low
4   80000            High


In [35]:
df

,Age,Salary,City,Experience_Level,Purchased,Experience_Score,Age_Group,Salary_Log,Age_Salary_Interaction,Income_Category
0,25,50000,hyderabad,junior,no,1,Young,10.819778,1250000,Low
1,30,60000,chennai,mid,yes,2,Young,11.002100,1800000,Low
2,22,45000,delhi,junior,no,1,Young,10.714418,990000,Low
3,35,70000,mumbai,senior,yes,3,Adult,11.156251,2450000,Low
4,40,80000,hyderabad,senior,yes,3,Adult,11.289782,3200000,High
5,28,52000,delhi,mid,no,2,Young,10.858999,1456000,Low
6,32,62000,chennai,junior,yes,1,Adult,11.034890,1984000,Low
7,45,90000,mumbai,senior,yes,3,Adult,11.407565,4050000,High
8,29,48000,delhi,mid,no,2,Young,10.778956,1392000,Low
9,50,120000,hyderabad,senior,yes,3,Senior,11.695247,6000000,High


Why powerful?

Domain knowledge > automatic methods

# Date-Time Feature Extraction

In [36]:
# Add a date column:
df['Join_Date'] = pd.date_range(start='2026-01-01', periods=len(df))

df['Join_Year'] = df['Join_Date'].dt.year
df['Join_Month'] = df['Join_Date'].dt.month
df['Join_Day'] = df['Join_Date'].dt.day

print(df[['Join_Date','Join_Year','Join_Month','Join_Day']])


    Join_Date  Join_Year  Join_Month  Join_Day
0  2026-01-01       2026           1         1
1  2026-01-02       2026           1         2
2  2026-01-03       2026           1         3
3  2026-01-04       2026           1         4
4  2026-01-05       2026           1         5
5  2026-01-06       2026           1         6
6  2026-01-07       2026           1         7
7  2026-01-08       2026           1         8
8  2026-01-09       2026           1         9
9  2026-01-10       2026           1        10
10 2026-01-11       2026           1        11


# Feature Crossing

In [37]:
# Combine two categorical features.
df['City_Experience'] = df['City'] + "_" + df['Experience_Level']

print(df[['City','Experience_Level','City_Experience']].head())


        City Experience_Level   City_Experience
0  hyderabad           junior  hyderabad_junior
1    chennai              mid       chennai_mid
2      delhi           junior      delhi_junior
3     mumbai           senior     mumbai_senior
4  hyderabad           senior  hyderabad_senior


In [38]:
df

,Age,Salary,City,Experience_Level,Purchased,Experience_Score,Age_Group,Salary_Log,Age_Salary_Interaction,Income_Category,Join_Date,Join_Year,Join_Month,Join_Day,City_Experience
0,25,50000,hyderabad,junior,no,1,Young,10.819778,1250000,Low,2026-01-01,2026,1,1,hyderabad_junior
1,30,60000,chennai,mid,yes,2,Young,11.002100,1800000,Low,2026-01-02,2026,1,2,chennai_mid
2,22,45000,delhi,junior,no,1,Young,10.714418,990000,Low,2026-01-03,2026,1,3,delhi_junior
3,35,70000,mumbai,senior,yes,3,Adult,11.156251,2450000,Low,2026-01-04,2026,1,4,mumbai_senior
4,40,80000,hyderabad,senior,yes,3,Adult,11.289782,3200000,High,2026-01-05,2026,1,5,hyderabad_senior
5,28,52000,delhi,mid,no,2,Young,10.858999,1456000,Low,2026-01-06,2026,1,6,delhi_mid
6,32,62000,chennai,junior,yes,1,Adult,11.034890,1984000,Low,2026-01-07,2026,1,7,chennai_junior
7,45,90000,mumbai,senior,yes,3,Adult,11.407565,4050000,High,2026-01-08,2026,1,8,mumbai_senior
8,29,48000,delhi,mid,no,2,Young,10.778956,1392000,Low,2026-01-09,2026,1,9,delhi_mid
9,50,120000,hyderabad,senior,yes,3,Senior,11.695247,6000000,High,2026-01-10,2026,1,10,hyderabad_senior


# FEATURE SCALING

Feature Scaling = Bringing all numerical features to similar range.

Why Scaling Is Important?

Scaling REQUIRED for:

Logistic Regression

KNN

SVM

Neural Networks

PCA

Gradient Descent based models

Scaling NOT required for:

Decision Trees

Random Forest

XGBoost

LightGBM

In [39]:
import numpy as np
import pandas as pd

data = {
    "Age": [20, 25, 30, 35, 40],
    "Salary": [30000, 50000, 70000, 90000, 110000]
}

df = pd.DataFrame(data)
print("Original Data:\n", df)


Original Data:
    Age  Salary
0   20   30000
1   25   50000
2   30   70000
3   35   90000
4   40  110000


# StandardScaler

In [40]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaled_data = scaler.fit_transform(df)

print("Standard Scaled:\n", scaled_data)


Standard Scaled:
 [[-1.41421356 -1.41421356]
 [-0.70710678 -0.70710678]
 [ 0.          0.        ]
 [ 0.70710678  0.70710678]
 [ 1.41421356  1.41421356]]


# MinMaxScaler

In [41]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(df)

print("MinMax Scaled:\n", scaled_data)


MinMax Scaled:
 [[0.   0.  ]
 [0.25 0.25]
 [0.5  0.5 ]
 [0.75 0.75]
 [1.   1.  ]]


# RobustScaler

In [42]:
from sklearn.preprocessing import RobustScaler

scaler = RobustScaler()
scaled_data = scaler.fit_transform(df)

print("Robust Scaled:\n", scaled_data)


Robust Scaled:
 [[-1.  -1. ]
 [-0.5 -0.5]
 [ 0.   0. ]
 [ 0.5  0.5]
 [ 1.   1. ]]


# MaxAbsScaler

In [43]:
from sklearn.preprocessing import MaxAbsScaler

scaler = MaxAbsScaler()
scaled_data = scaler.fit_transform(df)

print("MaxAbs Scaled:\n", scaled_data)


MaxAbs Scaled:
 [[0.5        0.27272727]
 [0.625      0.45454545]
 [0.75       0.63636364]
 [0.875      0.81818182]
 [1.         1.        ]]


# Normalizer

In [44]:
from sklearn.preprocessing import Normalizer

scaler = Normalizer()
scaled_data = scaler.fit_transform(df)

print("Normalized Data:\n", scaled_data)


Normalized Data:
 [[6.66666519e-04 9.99999778e-01]
 [4.99999938e-04 9.99999875e-01]
 [4.28571389e-04 9.99999908e-01]
 [3.88888859e-04 9.99999924e-01]
 [3.63636340e-04 9.99999934e-01]]


# FEATURE SELECTION TECHNIQUES

In [45]:
import numpy as np
import pandas as pd

np.random.seed(42)

data = {
    'Age': np.random.randint(20, 60, 50),
    'Salary': np.random.randint(30000, 100000, 50),
    'Experience': np.random.randint(1, 20, 50),
    'Random_Noise1': np.random.randn(50),
    'Random_Noise2': np.random.randn(50),
}

df = pd.DataFrame(data)

# Target depends mostly on Salary + Experience
df['Purchased'] = (df['Salary'] + df['Experience']*1000 > 80000).astype(int)

print(df)


    Age  Salary  Experience  Random_Noise1  Random_Noise2  Purchased
0    58   97121           3       0.452936      -0.324491          1
1    48   99479           1      -0.166061      -0.205867          1
2    34   49457           3       0.214939      -1.440041          0
3    27   96557           5      -2.022315       1.190727          1
4    40   82995          15      -0.943057       1.299397          1
5    58   70757          14       1.403959      -0.867146          1
6    38   39692           3      -0.018551       0.617641          0
7    42   75758           1      -1.673505       1.217071          0
8    30   95697           5      -1.072532       0.226288          1
9    30   67065          14      -0.992586       0.847401          1
10   43   62606           7       0.102348       0.174833          0
11   55   41534           9      -0.432609      -1.216855          0
12   59   70397          15      -0.659182       1.049347          1
13   43   31016          15       

# FILTER METHODS

# Correlation Method

In [46]:
print(df.corr())


                    Age    Salary  Experience  Random_Noise1  Random_Noise2  \
Age            1.000000  0.027660   -0.007430       0.080630      -0.115934   
Salary         0.027660  1.000000   -0.112283      -0.048881       0.103177   
Experience    -0.007430 -0.112283    1.000000       0.050386       0.110838   
Random_Noise1  0.080630 -0.048881    0.050386       1.000000      -0.145565   
Random_Noise2 -0.115934  0.103177    0.110838      -0.145565       1.000000   
Purchased      0.121303  0.834818    0.141643       0.032478       0.161045   

               Purchased  
Age             0.121303  
Salary          0.834818  
Experience      0.141643  
Random_Noise1   0.032478  
Random_Noise2   0.161045  
Purchased       1.000000  


In [47]:
# Check correlation with target:
print(df.corr()['Purchased'].sort_values(ascending=False))


Purchased        1.000000
Salary           0.834818
Random_Noise2    0.161045
Experience       0.141643
Age              0.121303
Random_Noise1    0.032478
Name: Purchased, dtype: float64


# Chi-Square Test (for categorical target)

In [48]:
from sklearn.feature_selection import SelectKBest, chi2

X = df[['Age','Salary','Experience']]
y = df['Purchased']

selector = SelectKBest(score_func=chi2, k=2)
X_new = selector.fit_transform(X, y)

print("Selected features:", selector.get_support())

# Meaning Salary and Experience selected.

Selected features: [False  True  True]


# WRAPPER METHODS

# Recursive Feature Elimination (RFE)

In [49]:
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import RFE

model = LogisticRegression(max_iter=1000)

rfe = RFE(model, n_features_to_select=2)
rfe.fit(X, y)

print("Selected Features:", rfe.support_)


Selected Features: [ True False  True]


# EMBEDDED METHODS

# L1 Regularization (Lasso)

In [50]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(penalty='l1', solver='liblinear')
model.fit(X, y)

print("Coefficients:", model.coef_)

# Features with zero coefficients → removed.

Coefficients: [[-0.01299816  0.00011175  0.10488319]]


# Tree-Based Feature Importance

In [51]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()
rf.fit(X, y)

importance = rf.feature_importances_

for name, score in zip(X.columns, importance):
    print(name, ":", score)

# High score → important feature.

Age : 0.12242508088939298
Salary : 0.7473212110248492
Experience : 0.13025370808575784


# PCA (Dimensionality Reduction)

In [52]:
# Not feature selection, but dimensionality reduction.
from sklearn.decomposition import PCA

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X)

print("Explained Variance Ratio:", pca.explained_variance_ratio_)


Explained Variance Ratio: [9.99999672e-01 2.71071414e-07]


# PHASE 1 – COMPLETE END-TO-END IMPLEMENTATION

In [53]:
# ================================
# PHASE 1 – COMPLETE ML PIPELINE
# ================================

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.impute import SimpleImputer, KNNImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from sklearn.ensemble import RandomForestClassifier


# --------------------------------
# CREATE ADVANCED DATASET
# --------------------------------

np.random.seed(42)

data = {
    "Age": [25, 30, 22, 35, 40, np.nan, 28, 32, 45, 29, 50, 27],
    "Salary": [50000, 60000, 45000, np.nan, 80000, 52000, 48000, 62000, 90000, -1, 120000, 55000],
    "City": ["Hyderabad", "Chennai", "Delhi", "Mumbai", np.nan,
             "Hyderabad", "Delhi", "Chennai", "Mumbai", "Delhi", "Hyderabad", "Chennai"],
    "Education_Level": ["Bachelor", "Master", "Bachelor", "PhD", "Master",
                        "Bachelor", "Master", "PhD", "Bachelor", "Master", "PhD", None],
    "Experience_Level": ["Junior", "Mid", "Junior", "Senior", "Senior",
                         "Mid", "Junior", "Senior", "Mid", "Junior", "Senior", "Mid"],
    "Purchased": ["No", "Yes", "No", "Yes", "Yes",
                  "No", "No", "Yes", "Yes", "No", "Yes", "No"]
}

df = pd.DataFrame(data)

print("Original Dataset:\n")
print(df)


Original Dataset:

     Age    Salary       City Education_Level Experience_Level Purchased
0   25.0   50000.0  Hyderabad        Bachelor           Junior        No
1   30.0   60000.0    Chennai          Master              Mid       Yes
2   22.0   45000.0      Delhi        Bachelor           Junior        No
3   35.0       NaN     Mumbai             PhD           Senior       Yes
4   40.0   80000.0        NaN          Master           Senior       Yes
5    NaN   52000.0  Hyderabad        Bachelor              Mid        No
6   28.0   48000.0      Delhi          Master           Junior        No
7   32.0   62000.0    Chennai             PhD           Senior       Yes
8   45.0   90000.0     Mumbai        Bachelor              Mid       Yes
9   29.0      -1.0      Delhi          Master           Junior        No
10  50.0  120000.0  Hyderabad             PhD           Senior       Yes
11  27.0   55000.0    Chennai            None              Mid        No


# DATA CLEANING - CHECK MISSING VALUES

In [54]:
print("\nMissing Values:\n")
print(df.isnull().sum())



Missing Values:

Age                 1
Salary              1
City                1
Education_Level     1
Experience_Level    0
Purchased           0
dtype: int64


# HANDLE INVALID VALUES


In [55]:
# Replace invalid salary (-1) with NaN
df['Salary'] = df['Salary'].replace(-1, np.nan)
df['Education_Level'] = df['Education_Level'].replace({None:'PhD'})
print("\nAfter replacing invalid salary:\n")
print(df.isnull().sum())



After replacing invalid salary:

Age                 1
Salary              2
City                1
Education_Level     0
Experience_Level    0
Purchased           0
dtype: int64


# REMOVE DUPLICATES

In [56]:
df.drop_duplicates(inplace=True)
print("\nShape after removing duplicates:", df.shape)



Shape after removing duplicates: (12, 6)


# STANDARDIZE TEXT (INCONSISTENT DATA)

In [57]:
df['City'] = df['City'].str.lower()
df['Education_Level'] = df['Education_Level'].str.lower()
df['Experience_Level'] = df['Experience_Level'].str.lower()
df['Purchased'] = df['Purchased'].str.lower()

print("\nAfter standardizing text:\n")
print(df.head())



After standardizing text:

    Age   Salary       City Education_Level Experience_Level Purchased
0  25.0  50000.0  hyderabad        bachelor           junior        no
1  30.0  60000.0    chennai          master              mid       yes
2  22.0  45000.0      delhi        bachelor           junior        no
3  35.0      NaN     mumbai             phd           senior       yes
4  40.0  80000.0        NaN          master           senior       yes


# HANDLE OUTLIERS (IQR METHOD)

In [58]:

Q1 = df['Salary'].quantile(0.25)
Q3 = df['Salary'].quantile(0.75)
IQR = Q3 - Q1

upper = Q3 + 1.5 * IQR
lower = Q1 - 1.5 * IQR
#df['Salary'] = np.where(df['Salary'] > upper, upper, df['Salary'])
outliers = df[(df['Salary'] < lower) | (df['Salary'] > upper)]
print("\nAfter capping outliers:\n")
print(outliers)



After capping outliers:

     Age    Salary       City Education_Level Experience_Level Purchased
10  50.0  120000.0  hyderabad             phd           senior       yes


# HANDLE MISSING VALUES

In [59]:
# Numerical Imputation
num_imputer = SimpleImputer(strategy='median')
df[['Age', 'Salary']] = num_imputer.fit_transform(df[['Age', 'Salary']])

# Categorical Imputation
cat_imputer = SimpleImputer(strategy='most_frequent')
df[['City', 'Education_Level']] = cat_imputer.fit_transform(
    df[['City', 'Education_Level']]
)

print("\nAfter Imputation:\n")
print(df)



After Imputation:

     Age    Salary       City Education_Level Experience_Level Purchased
0   25.0   50000.0  hyderabad        bachelor           junior        no
1   30.0   60000.0    chennai          master              mid       yes
2   22.0   45000.0      delhi        bachelor           junior        no
3   35.0   57500.0     mumbai             phd           senior       yes
4   40.0   80000.0    chennai          master           senior       yes
5   30.0   52000.0  hyderabad        bachelor              mid        no
6   28.0   48000.0      delhi          master           junior        no
7   32.0   62000.0    chennai             phd           senior       yes
8   45.0   90000.0     mumbai        bachelor              mid       yes
9   29.0   57500.0      delhi          master           junior        no
10  50.0  120000.0  hyderabad             phd           senior       yes
11  27.0   55000.0    chennai             phd              mid        no


# CHECK IMBALANCE

In [72]:
print("\nClass Distribution:\n")
print(df['Purchased'].value_counts())



Class Distribution:

Purchased
no     6
yes    6
Name: count, dtype: int64


# FEATURE ENGINEERING - CREATE NEW FEATURES

In [73]:
# Map experience to numeric score
exp_map = {'junior':1, 'mid':2, 'senior':3}
df['Experience_Score'] = df['Experience_Level'].map(exp_map)

# Create salary log
df['Salary_Log'] = np.log(df['Salary'])

# Create age group
df['Age_Group'] = pd.cut(df['Age'], bins=[18,30,45,60], labels=['young','adult','senior'])

print("\nAfter Feature Engineering:\n")
print(df.head())



After Feature Engineering:

    Age   Salary       City Education_Level Experience_Level Purchased  \
0  25.0  50000.0  hyderabad        bachelor           junior        no   
1  30.0  60000.0    chennai          master              mid       yes   
2  22.0  45000.0      delhi        bachelor           junior        no   
3  35.0  57500.0     mumbai             phd           senior       yes   
4  40.0  80000.0    chennai          master           senior       yes   

   Experience_Score  Salary_Log Age_Group  
0                 1   10.819778     young  
1                 2   11.002100     young  
2                 1   10.714418     young  
3                 3   10.959540     adult  
4                 3   11.289782     adult  


In [74]:
df

,Age,Salary,City,Education_Level,Experience_Level,Purchased,Experience_Score,Salary_Log,Age_Group
0,25.0,50000.0,hyderabad,bachelor,junior,no,1,10.819778,young
1,30.0,60000.0,chennai,master,mid,yes,2,11.002100,young
2,22.0,45000.0,delhi,bachelor,junior,no,1,10.714418,young
3,35.0,57500.0,mumbai,phd,senior,yes,3,10.959540,adult
4,40.0,80000.0,chennai,master,senior,yes,3,11.289782,adult
5,30.0,52000.0,hyderabad,bachelor,mid,no,2,10.858999,young
6,28.0,48000.0,delhi,master,junior,no,1,10.778956,young
7,32.0,62000.0,chennai,phd,senior,yes,3,11.034890,adult
8,45.0,90000.0,mumbai,bachelor,mid,yes,2,11.407565,adult
9,29.0,57500.0,delhi,master,junior,no,1,10.959540,young


# FEATURE SCALING + PREPROCESSING

In [76]:
# SPLIT DATA
X = df.drop('Purchased', axis=1)
y = df['Purchased']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("\nTrain Shape:", X_train.shape)
print("Test Shape:", X_test.shape)



Train Shape: (9, 8)
Test Shape: (3, 8)


# DEFINE FEATURE TYPES

In [77]:
numeric_features = ['Age', 'Salary', 'Experience_Score', 'Salary_Log']
nominal_features = ['City', 'Education_Level', 'Age_Group']
ordinal_features = ['Experience_Level']


# CREATE PIPELINES

In [65]:
numeric_pipeline = Pipeline([
    ('scaler', StandardScaler())
])

nominal_pipeline = Pipeline([
    ('encoder', OneHotEncoder(handle_unknown='ignore'))
])

ordinal_pipeline = Pipeline([
    ('encoder', OrdinalEncoder(categories=[['junior','mid','senior']]))
])

preprocessor = ColumnTransformer([
    ('num', numeric_pipeline, numeric_features),
    ('nom', nominal_pipeline, nominal_features),
    ('ord', ordinal_pipeline, ordinal_features)
])


# ADD MODEL

In [66]:
pipeline = Pipeline([
    ('preprocessing', preprocessor),
    ('model', LogisticRegression())
])


# MODEL TRAINING

In [67]:
pipeline.fit(X_train, y_train)

print("\nModel trained successfully.")



Model trained successfully.


# PREDICT

In [68]:
y_pred = pipeline.predict(X_test)

print("\nPredictions:", y_pred)
print("Actual:", y_test.values)



Predictions: ['yes' 'no' 'no']
Actual: ['yes' 'no' 'no']


# EVALUATION - MODEL PERFORMANCE

In [69]:
print("\nAccuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))



Accuracy: 1.0

Classification Report:

              precision    recall  f1-score   support

          no       1.00      1.00      1.00         2
         yes       1.00      1.00      1.00         1

    accuracy                           1.00         3
   macro avg       1.00      1.00      1.00         3
weighted avg       1.00      1.00      1.00         3



# FEATURE SELECTION (EMBEDDED)

# RANDOM FOREST FEATURE IMPORTANCE

In [70]:
rf = RandomForestClassifier()
rf.fit(X_train[numeric_features], y_train)

for name, score in zip(numeric_features, rf.feature_importances_):
    print(name, ":", score)


Age : 0.24297857142857143
Salary : 0.41342142857142855
Experience_Score : 0.10640000000000001
Salary_Log : 0.2372


# HYPERPARAMETER TUNING

# GRID SEARCH

In [71]:
param_grid = {
    'model__C': [0.1, 1, 10]
}

grid = GridSearchCV(pipeline, param_grid, cv=3)
grid.fit(X_train, y_train)

print("\nBest Parameters:", grid.best_params_)



Best Parameters: {'model__C': 0.1}
