# NUMPY COMPLETE CHEATSHEET (ALL OPERATIONS)

# Array Creation - From list / tuple

In [51]:
a = np.array([1, 2, 3])
b = np.array((4, 5, 6))
print(a)
print(b)

[1 2 3]
[4 5 6]


# Zeros, Ones, Empty

In [52]:
c = np.zeros(5)
d = np.ones((2,3))
e = np.empty(4)
print(c)
print(d)
print(e)


[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[5. 6. 7. 8.]


# Range-based

In [53]:
a = np.arange(0, 10, 2)
b = np.linspace(0, 1, 5)
print(a)
print(b)

[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


# Identity / Diagonal

In [54]:
a = np.eye(3)
b = np.identity(3)
c = np.diag([1,2,3])
print(a)
print(b)
print(c)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


# Array Attributes

In [55]:
a = np.array([[2,3],
     [4,5]])
print(a.ndim)     # dimensions
print(a.shape)     # rows, columns
print(a.size)      # total elements
print(a.dtype)     # data type
print(a.itemsize)  # bytes per element


2
(2, 2)
4
int32
4


# Data Types

In [56]:
a = np.array([1,2,3], dtype=float)
b = np.array([1,2,3], dtype=int)
c = np.array([1,0,1], dtype=bool)
print(a)
print(b)
print(c)
# Type conversion:
d = c.astype(float)
print(d)

[1. 2. 3.]
[1 2 3]
[ True False  True]
[1. 0. 1.]


# Indexing & Slicing

In [57]:
# 1D Indexing
a = np.array([10,20,30,40,50])

print(a[0])
print(a[-1])
print(a[1:4])
print(a[:3])
print(a[::2])


10
50
[20 30 40]
[10 20 30]
[10 30 50]


In [58]:
# 2D Indexing
b = np.array([[1,2],[3,4],[5,6]])
print(b[0,1])
print(b[:,0])
print(b[1,:])


2
[1 3 5]
[3 4]


# Array Reshaping

In [59]:
a = np.array([10,20,30,40,50,60])
print(a.reshape(2,3)) # Changes the shape of the array
print(a.flatten()) # Converts array into 1D. Always returns a copy (new memory)
print(a.ravel()) # Converts array into 1D. Returns a view if possible (not a copy)
b = np.array([[1,2],
            [3,4],
            [5,6]])
print(b.transpose()) # Swaps axes (rows ↔ columns)
print(b.T) # Shortcut (property) for transpose()


[[10 20 30]
 [40 50 60]]
[10 20 30 40 50 60]
[10 20 30 40 50 60]
[[1 3 5]
 [2 4 6]]
[[1 3 5]
 [2 4 6]]


# Mathematical Operations

In [60]:
# Arithmetic
x = np.array([[1,2],
            [3,4]])
y = np.array([[5,6],
            [7,8]])
print(np.add(x, y))        # x + y
print(np.subtract(x, y))    # x - y
print(np.multiply(x, y))     # x * y
print(np.divide(x, y))       # x / y
print(np.power(x, y))        # x ** y
print(np.mod(x, y))          # remainder
print(np.remainder(x, y))
print(np.floor_divide(x, y))


[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[    1    64]
 [ 2187 65536]]
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[0 0]
 [0 0]]


In [63]:
# Rounding & Approximation
x = [1,2,3.3,4.5,5.5,6.5,7.7,8]
print(np.round(x)) # round to nearest even
print(np.around(x)) # round is just an alias for around
print(np.floor(x)) 
print(np.ceil(x))
print(np.trunc(x))
print(np.fix(x))


[1. 2. 3. 4. 6. 6. 8. 8.]
[1. 2. 3. 4. 6. 6. 8. 8.]
[1. 2. 3. 4. 5. 6. 7. 8.]
[1. 2. 4. 5. 6. 7. 8. 8.]
[1. 2. 3. 4. 5. 6. 7. 8.]
[1. 2. 3. 4. 5. 6. 7. 8.]


In [64]:
# Exponential & Logarithmic
np.exp(x)
np.exp2(x)
np.expm1(x)

np.log(x)
np.log10(x)
np.log2(x)
np.log1p(x)


array([0.69314718, 1.09861229, 1.45861502, 1.70474809, 1.87180218,
       2.01490302, 2.16332303, 2.19722458])

In [65]:
# POWER & ROOT OPERATIONS
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])
np.sqrt(x)
np.cbrt(x)
np.square(x)
np.power(x, 2)
np.hypot(x, y)


array([5.09901951, 6.32455532, 7.61577311, 8.94427191])

In [66]:
# TRIGONOMETRIC FUNCTIONS
np.sin(a)
np.cos(a)
np.tan(a)


array([ 0.64836083,  2.23716094, -6.4053312 , -1.11721493, -0.27190061,
        0.32004039])

In [67]:
# Inverse
x = np.array([1])
y = np.array([5])
np.arcsin(x)
np.arccos(x)
np.arctan(x)
np.arctan2(x, y)

array([0.19739556])

In [69]:
# Hyperbolic
a = np.array([180])
b = np.array([60])
np.sinh(a)
np.cosh(a)
np.tanh(a)
np.arcsinh(a)
np.arccosh(a)
np.arctanh(a)


C:\Users\prasa\AppData\Local\Temp\ipykernel_25092\2766440976.py:9: RuntimeWarning: invalid value encountered in arctanh
  np.arctanh(a)


array([nan])

In [70]:
# DEGREE ↔ RADIAN CONVERSION
np.deg2rad(a)
np.rad2deg(a)
np.degrees(a)
np.radians(a)


array([3.14159265])

In [ ]:
# bitwise_and

# bitwise_or

# bitwise_xor

# invert

# left_shift

# right_shift

# binary_repr

In [ ]:
# equal

# not_equal

# greater

# greater_equal

# less

# less_equal

# allclose

# isclose

In [ ]:
# logical_and

# logical_or

# logical_xor

# logical_not

# Statistical Operations

In [ ]:
# min

# max

# argmin

# argmax

# ptp

# mean

# median

# Dispersion & Percentiles

In [ ]:
# std
# var
# percentile
# quantile

# Aggregation & Reduction

In [ ]:
# sum

# prod

# cumsum

# cumprod

# diff

# ediff1d


# Sorting & Searching

In [ ]:
# sort

# argsort

# lexsort

# partition

# argpartition


# where

# searchsorted

# count_nonzero

# Set Operations

In [ ]:
# unique

# intersect1d

# union1d

# setdiff1d

# setxor1d

# in1d

# isin

# Linear Algebra (numpy.linalg)

In [ ]:
# dot

# matmul

# vdot

# inner

# outer

# einsum

# cross

# tensordot

# Matrix operations

In [ ]:
# det

# inv

# pinv

# matrix_rank

# trace

# norm

# solve

# lstsq

# eig

# eigvals

# svd

# qr

# cholesky

# Random Number Generation (numpy.random)

In [ ]:
# # Generators
# default_rng

# seed

# # Distributions
# rand

# randn

# randint

# random

# uniform

# normal

# binomial

# poisson

# exponential

# beta

# gamma

# lognormal

# multivariate_normal

# # Sampling

# choice

# shuffle

# permutation


# Input / Output Operations


In [ ]:
# save

# savez

# savez_compressed

# load

# savetxt

# loadtxt

# genfromtxt

# memmap

# Masked Arrays (numpy.ma)

In [ ]:
# masked_array

# mask_or

# mask_and

# getmask

# getdata

# filled

# count

# mean

# sum

# Broadcasting System

In [ ]:
# Broadcasting rules

# Scalar → array expansion

# Shape compatibility

# Implicit vectorization